### ISSUE TITLE
broken link for https://presentations.huangzhimin.com

### ISSUE THREAD

**Issue by liijunwei** [flyerhzm/huangzhimin.com#4]
Hi, this is a reminder that your presentation page link is broken

https://presentations.huangzhimin.com

https://github.com/flyerhzm/huangzhimin.com/blob/1ad764315b3de1fdb6154403d7056a3930e9f55b/index.html#L25

would like to explore them after it's fixed 🙏

**Comment by flyerhzm** [comment]
@liijunwei it's fixed, thanks for figuring it out.
